version: '3'
services:
  event-service:
    depends_on:
      - mq-service
    build: ./event-service
    volumes:
      - db_event:/home/pushkind/db
    restart: unless-stopped
    environment:
      - DB_URL
      - SECRET_KEY
      - CONFIGURATION_SETUP

  frontend:
    depends_on:
      - mq-service
    build: ./frontend
    volumes:
      - upload:/home/pushkind/app/static/upload
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    environment:
      - SECRET_KEY
      - CONFIGURATION_SETUP
      - APPLICATION_TITLE

  hub-service:
    depends_on:
      - mq-service
    build: ./hub-service
    volumes:
      - db_hub:/home/pushkind/db
    restart: unless-stopped
    environment:
      - DB_URL
      - SECRET_KEY
      - CONFIGURATION_SETUP

  order-service:
    depends_on:
      - mq-service
    build: ./order-service
    volumes:
      - db_order:/home/pushkind/db
    restart: unless-stopped
    environment:
      - DB_URL
      - SECRET_KEY
      - CONFIGURATION_SETUP

  project-service:
    depends_on:
      - mq-service
    build: ./project-service
    volumes:
      - db_project:/home/pushkind/db
    restart: unless-stopped
    environment:
      - DB_URL
      - SECRET_KEY
      - CONFIGURATION_SETUP

  tender-service:
    depends_on:
      - mq-service
    build: ./tender-service
    volumes:
      - db_tender:/home/pushkind/db
    restart: unless-stopped
    environment:
      - DB_URL
      - SECRET_KEY
      - CONFIGURATION_SETUP

  user-service:
    depends_on:
      - mq-service
    build: ./user-service
    volumes:
      - db_user:/home/pushkind/db
    restart: unless-stopped
    environment:
      - DB_URL
      - SECRET_KEY
      - CONFIGURATION_SETUP

  mq-service:
    image: rabbitmq:3-management-alpine
    volumes:
      - mq:/var/lib/rabbitmq/
    ports:
      - 127.0.0.1:15672:15672
    restart: unless-stopped

volumes:
  db_event:
  db_hub:
  db_order:
  db_project:
  db_tender:
  db_user:
  mq:
  upload:


