"""empty message

Revision ID: 1897eca78296
Revises: 
Create Date: 2022-10-05 22:55:47.298949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1897eca78296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('type', sa.Enum('commented', 'approved', 'disapproved', 'quantity', 'duplicated', 'purchased', 'exported', 'merged', 'dealdone', 'income_statement', 'cashflow_statement', 'site', 'measurement', 'splitted', 'project', 'notification', 'cancelled', name='eventtype'), nullable=False),
    sa.Column('data', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_event_order_id'), 'order_event', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_event_user_id'), 'order_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_event_user_id'), table_name='order_event')
    op.drop_index(op.f('ix_order_event_order_id'), table_name='order_event')
    op.drop_table('order_event')
    # ### end Alembic commands ###
